### PR TITLE
Fix for IndexOutOfBoundsException in sarif placeholder 

### LINKED ISSUE #2632: [4.8.0] SarifBugReporter causes IndexOutOfBoundsException
```console
> Task :jcache:spotbugsMain
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at edu.umd.cs.findbugs.sarif.Placeholder.toArgument(Placeholder.java:31)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.lambda$processResult$6(BugCollectionAnalyser.java:123)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.processResult(BugCollectionAnalyser.java:124)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.lambda$new$1(BugCollectionAnalyser.java:52)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at edu.umd.cs.findbugs.sarif.BugCollectionAnalyser.<init>(BugCollectionAnalyser.java:46)
        at edu.umd.cs.findbugs.sarif.SarifBugReporter.processRuns(SarifBugReporter.java:54)
        at edu.umd.cs.findbugs.sarif.SarifBugReporter.finish(SarifBugReporter.java:41)
        at edu.umd.cs.findbugs.BugReportDispatcher.lambda$forEach$13(BugReportDispatcher.java:124)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at edu.umd.cs.findbugs.BugReportDispatcher.forEach(BugReportDispatcher.java:129)
        at edu.umd.cs.findbugs.BugReportDispatcher.finish(BugReportDispatcher.java:43)
        at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
        at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
        at edu.umd.cs.findbugs.DelegatingBugReporter.finish(DelegatingBugReporter.java:89)
        at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1165)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
        at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
        at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
```

### PR DESCRIPTION
**Pull request by gtoison**
When the bug description has a placeholder for a non-existent annotation the sarif placeholder class causes a IndexOutOfBoundsException

This is most likely a side effect of #2627 

Fixes #2632

### CODE REVIEW

File: spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Placeholder.java [hunk 1]
```diff
@@ -28,6 +28,12 @@ class Placeholder {
 
     @NonNull
     String toArgument(List<? extends BugAnnotation> bugAnnotations, @Nullable ClassAnnotation primaryClass) {
-        return bugAnnotations.get(index).format(key, primaryClass);
+        if (index < 0) {
```
Comment (hazendaz) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Placeholder.java:31]: @gtoison Can you combine the 'if' here?

Comment (gtoison) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Placeholder.java:31]: The two look similar but are different (< vs. >), I used the same format as edu.umd.cs.findbugs.FindBugsMessageFormat#format so the same problem will produce a similar output

Comment (hazendaz) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Placeholder.java:31]: Ah, thanks, I looked at that multiple times but wasn't seeing it.  All good.

**Review by hazendaz — APPROVED** [review]
