### PR TITLE
Avoid exception when inspecting empty switch statements

### LINKED ISSUE #2995: Index out of bounds for empty switch
Since update to 4.8.4 I'm getting this
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
      At edu.umd.cs.findbugs.SwitchHandler.enterSwitch(SwitchHandler.java:90)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.analyzeMethod(FindDeadLocalStores.java:283)
      At edu.umd.cs.findbugs.detect.FindDeadLocalStores.visitClassContext(FindDeadLocalStores.java:198)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$1(FindBugs2.java:1108)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At edu.umd.cs.findbugs.CurrentThreadExecutorService.execute(CurrentThreadExecutorService.java:86)
      At java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1118)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:395)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1231)
 ```
 when analyzing a generaated class that contains
 ```
 switch(jjstateSet[--i]) {
   default : break;
}
```
and
```
switch(jjmatchedKind) {
      default :
         break;
   }
```
It could make sense to optimize the code generator, but I think it's still worth fixing the OutOfBounds problem in SpotBugs.

Possibly related to https://github.com/spotbugs/spotbugs/pull/2828

### PR DESCRIPTION
**Pull request by zbynek**
Fixes #2995 

The testcase reproduces the issue, at least with Java 11. For the fix itself I'm not 100% sure it's the right approach

### CODE REVIEW

**Comment by gtoison** [comment]
Thanks for the PR! I have approved the run but spotless failed the build. Can you please run this and commit the changes?
gradlew spotlessApply

File: spotbugs/src/main/java/edu/umd/cs/findbugs/SwitchHandler.java [hunk 1]
```diff
@@ -290,5 +290,9 @@ public int getDefaultOffset() {
             }
             return switchPC + defaultOffset;
         }
+
+        public int getLastOffset() {
```
Comment (gtoison) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/SwitchHandler.java:294]: Can you please make this method private?

**Review by gtoison — CHANGES_REQUESTED** [review]
Aside from the small comment can you please add a new entry in the [changelog](https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md)?
Thank you very much for the fix!

**Review by ThrawnCA — APPROVED** [review]

**Review by gtoison — APPROVED** [review]
