### PR TITLE
Perform Bug-Reporter deduplication based on target files

### LINKED ISSUE #2047: Specifying the same report multiple times results in output issues
For reasons I don't want to get into here, I accidentally ran spotbugs with the following abridged command: 

```
> java -jar /spotbugs/spotbugs.jar -noClassOk -xml:withMessages=spotbugs.xml [...] -xml:withMessages=spotbugs.xml -onlyAnalyze com.example.SomeClass dist/*.ear
```

Specifying the **same** XML report output multiple times seems to consistently generate a non-parseable XML file on the `FileStats` section, given sufficiently many files analyzed.
It seems that there is some output flushing issue between two instances of the XML reporter. I assume that also applies for other reporters.

I'd expect a reporter to always generate valid data of its output format. Spotbugs should at least warn me about reporters fighting over a file (or even throw an error), especially when generating multiple reports using different options (i.e. `-xml:withMessages=spotbugs.xml -xml:minimal=spotbugs.xml`

### PR DESCRIPTION
**Pull request by Vogel612**
This is attempt number two to fix #2047, after the initial attempt broke stylesheet behavior and was reverted.

The first attempt at this was in PR #2894, subsequently reverted in #3038 to fix issue #2969

### CODE REVIEW

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java [hunk 1]
```diff
@@ -78,4 +80,28 @@ void htmlReportWithOption() throws IOException {
         assertTrue(xdocsFile.toFile().isFile());
         assertTrue(textFile.toFile().isFile());
     }
+
+    @Test
+    void sharedOutputFilesAreNotDuplicated() throws Exception {
```
Comment (JuditKnoll) [inline spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java:85]: Can you please add a test where not the same path is added, but two paths refer to the same location? E.g. the first path is `tempFile.xml` and the second one is `tempDir/../tempFile.xml` (obviously without calling `getAbsolutePath()` or canonizing the paths in the test.)

**Review by JuditKnoll — CHANGES_REQUESTED** [review]

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java (hunk 1 above)
Comment (Vogel612) [reply spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java:85]: What would be the expected behavior for that case? The original intention of the Bugreport was to make this use only a single outputstream, i.e. only a single reporter, which would imply canonicalizing the path in the underlying code...

File: spotbugs/src/main/java/edu/umd/cs/findbugs/TextUICommandLine.java [hunk 2]
```diff
@@ -816,4 +818,19 @@ private void handleAnalyzeFromFile(String filePath) throws IOException {
     private UserPreferences getUserPreferences() {
         return project.getConfiguration();
     }
+
+    /**
+     * Adds a reporter to the aggregating list of reporters, assuming it does not duplicate a known reporter.
```
Comment (gtoison) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/TextUICommandLine.java:823]: I think the "assuming" bit could be rephrased, because it is ignoring the reporter in case it is deemed to be a duplicate

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java (hunk 1 above)
Comment (JuditKnoll) [reply spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java:85]: IMO the same as if the same file is added, so that, it is not duplicated.

Comment (Vogel612) [reply spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java:85]: Added test case `deduplicationUsesCanonicalPaths`

File: spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java [hunk 3]
```diff
@@ -47,6 +47,8 @@ public abstract class TextUIBugReporter extends AbstractBugReporter implements C
 
     private boolean applySuppressions = false;
 
+    private String deduplicationKey = null;
```
[the remark this answers is not in the document]
Comment (Vogel612) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java]: renamed to `outputTarget`... not sure if that's better, but it's slightly closer to what you want I think?

File: spotbugs/src/main/java/edu/umd/cs/findbugs/TextUICommandLine.java (hunk 2 above)
Comment (Vogel612) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/TextUICommandLine.java]: reworded

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java [hunk 4]
```diff
@@ -78,4 +80,51 @@ void htmlReportWithOption() throws IOException {
...
+    void deduplicationUsesCanonicalPaths() throws Exception {
+        Path tmpdir = Files.createTempDirectory("spotbugs");
+        Files.createDirectory(tmpdir.resolve("sibling1"));
+        Files.createDirectory(tmpdir.resolve("sibling2"));
+        Path file = Files.createTempFile(tmpdir.resolve("sibling1"), "tempFile", ".xml");
+        Path altFile = tmpdir.resolve("sibling2").resolve("..").resolve(file.getFileName());
+        TextUICommandLine commandLine = new TextUICommandLine();
+        try (FindBugs2 findbugs = new FindBugs2()) {
+            commandLine.handleOption("-xml", "=" + file.toString());
+            commandLine.handleOption("-xml", "=" + altFile.toString());
```
Comment (JuditKnoll) [inline spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java:118]: These two `toString()`s are unnecessary.

**Review by JuditKnoll — APPROVED** [review]
One small issue, but otherwise LGTM.

**Review by ThrawnCA — APPROVED** [review]

**Review by JuditKnoll — APPROVED** [review]

File: spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java
Comment (hazendaz) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java:1]: Null is default on class variable so remove that.  On check on not null flip thr checks so null check is not necessary.  Instead of paths get.  Use path of.  Java replaced that and path.get just calls path.of.

 All else looks ok.

File: spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java [hunk 5]
```diff
@@ -240,6 +242,19 @@ protected void checkBugInstance(BugInstance bugInstance) {
         }
     }
 
+    public String getOutputTarget() {
+        return this.outputTarget;
```
Comment (ThrawnCA) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java:246]: Why use `this` when there is no local variable to confuse it with?

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java [hunk 6]
```diff
@@ -78,4 +80,51 @@ void htmlReportWithOption() throws IOException {
         assertTrue(xdocsFile.toFile().isFile());
         assertTrue(textFile.toFile().isFile());
     }
+
+    @Test
+    void sharedOutputFilesAreNotDuplicated() throws Exception {
+        Path file = Files.createTempFile("spotbugs", ".html");
+        TextUICommandLine commandLine = new TextUICommandLine();
+        try (FindBugs2 findbugs = new FindBugs2()) {
+            commandLine.handleOption("-html", "fancy-hist.xsl=" + file.toFile().getAbsolutePath());
```
Comment (ThrawnCA) [inline spotbugs-tests/src/test/java/edu/umd/cs/findbugs/TextUICommandLineTest.java:89]: Could extract the absolute path to a local variable.

File: spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java (hunk 5 above)
Comment (hazendaz) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/TextUIBugReporter.java:246]: I don't see harm there, personally I prefer objects to be qualified as its easier to understand where its defined.
