### PR TITLE
(SARIF) move exit code description and change behaviour of success flag

### LINKED ISSUE #2116: Sarif report and SuppressFBWarnings
Sarif report fails but check goal pass, I suppressed one line with `SuppressFBWarning` and I added a justification. 

Sarif says: `"executionSuccessful": false` and does not include the justification in the final report.

### LINKED ISSUE #2739: (SARIF) `exitSignalName` information should be moved to `exitCodeDescription`
Currently, the SARIF report uses the [`exitSignalName`](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790828) property to describe the exit code. However, per specification this property SHALL be absent if the process did not exit due to a signal.

I'd propose to move this information to the nearby [`exitCodeDescription`](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790827) property which is more fitting.

### PR DESCRIPTION
**Pull request by CodingDepot**
This PR makes changes to the `SarifBugReporter` in order to get it more in line with the [official SARIF specification](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html).

This includes the following Issues:
- Currently, The description of the exit code is stored in the property [`exitSignalName`](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790828). This property SHALL be absent when the process did not exit due to a signal. A better place for this information would be [`exitCodeDescription`](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790827). 
Closes #2739 .
- Currently, the SARIF report claims that the execution of the tool was not successful whenever bugs were found.
This goes against the intent of the [`executionSuccessful` property](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790831) as specified by the format.
This should close #2116 .

I considered adding the idea from #1918 (setting `executionSuccessful` to false when bugs were found AND the `failOnError` flag is set) but I could not find an easy link from the Reporter to the Task containing the flag value.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Comment by CodingDepot** [comment]
Added a small test that verifies a successful execution even when bugs were found. :slightly_smiling_face:

**Review by ThrawnCA — APPROVED** [review]

**Review by JuditKnoll — APPROVED** [review]

File: spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Invocation.java [hunk 1]
```diff
@@ -34,7 +35,7 @@ class Invocation {
     JsonObject toJsonObject() {
         JsonObject result = new JsonObject();
         result.addProperty("exitCode", exitCode);
-        result.addProperty("exitSignalName", exitSignalName);
+        result.addProperty("exitSignalName", exitCodeDescription);
```
Comment (hazendaz) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Invocation.java:38]: @CodingDepot I'm confused here, why change part of the property name but leave it as exitSignalName?  I'm not seeing the purpose of the name change as a result here.  Its a bit confusing to me now.  Can you explain?

Comment (CodingDepot) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Invocation.java]: No, you are completely right... I was being sloppy with the tacked on fix, I don't know how I missed that.
Upon review I found two more places where I failed to use the new property. :/
Thanks for having a closer look.

**Review by ThrawnCA — APPROVED** [review]

File: spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/SarifBugReporter.java [hunk 2]
```diff
@@ -87,8 +87,10 @@ private void processInvocations(JsonWriter jsonWriter, @NonNull Map<URI, String>
 
         int exitCode = ExitCodes.from(getQueuedErrors().size(), missingClasses.size(), getBugCollection().getCollection().size());
         Invocation invocation = new Invocation(exitCode,
-                getSignalName(exitCode), exitCode == 0,
-                execNotifications, configNotifications);
+                getSignalName(exitCode),
```
Comment (JuditKnoll) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/SarifBugReporter.java:90]: Since the second parameter of `Invocation`'s constructor changed to `exitCodeDescription` from `exitSignalName`, the name of this function (the definition is at line 146/148 in this file) also could be changed to represent this.

Comment (CodingDepot) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/SarifBugReporter.java]: Makes sense, the method name is changed in the latest commit.

**Comment by hazendaz** [comment]
@CodingDepot Can you fix merge conflicts here?

**Review by ThrawnCA — APPROVED** [review]
