### PR TITLE
StackOverFlowError in MultipleInstantiationsOfSingletons

### LINKED ISSUE #3280: MultipleInstantiationsOfSingletons.hasSynchronized() can produce stack overflow
When running latest spotbugs version 4.9.0 against my code I get the Exception below. I did not have time yet to find out which exact code in my code base is triggering this so I cannot give a reproducer yet.

```
`Exception in thread "main" edu.umd.cs.findbugs.ba.AnalysisException: Exception was thrown during analysis
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1110)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:309)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:399)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1223)
Caused by: java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at edu.umd.cs.findbugs.FindBugs2.lambda$analyzeApplication$3(FindBugs2.java:1112)
	... 5 more
Caused by: java.lang.StackOverflowError
	at java.base/java.util.ArrayList.indexOf(ArrayList.java:318)
	at java.base/java.util.ArrayList.contains(ArrayList.java:307)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:280)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
	at edu.umd.cs.findbugs.detect.MultipleInstantiationsOfSingletons.hasSynchronized(MultipleInstantiationsOfSingletons.java:287)
```

### PR DESCRIPTION
**Pull request by gtoison**
- Break the recursion in `MultipleInstantiationsOfSingletons`, this should fix #3280 
- Reordered some conditions so the trivial clauses are evaluated first

### CODE REVIEW

**Review by JuditKnoll — APPROVED** [review]
I'm sorry for the issue. Thank you for looking into and fixing it. You are super fast 😄

**Comment by gtoison** [comment]
No problem 😄 
I wonder how we could avoid these issues because the at the same time that problem was rather obvious in retrospect but also tricky to anticipate

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+import edu.umd.cs.findbugs.AbstractIntegrationTest;
+import org.junit.jupiter.api.Test;
+
+class Issue3280Test extends AbstractIntegrationTest {
+
+    @Test
+    void testIssue() {
+        performAnalysis("ghIssues/Issue3280.class");
+
+        assertNoBugType("SING_SINGLETON_IMPLEMENTS_CLONEABLE");
```
Comment (iloveeclipse) [inline spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java:12]: You could also add
`assertBugInClass("SING_SINGLETON_GETTER_NOT_SYNCHRONIZED", "Issue3280");`

Comment (gtoison) [reply spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java:12]: Good point, I have added this check as well!

File: spotbugs/src/main/java/edu/umd/cs/findbugs/detect/MultipleInstantiationsOfSingletons.java [hunk 2]
```diff
@@ -243,7 +243,7 @@ public void visitAfter(JavaClass javaClass) {
             }
         }
 
-        if (instanceGetterMethod != null && !hasSynchronized(instanceGetterMethod) && isInstanceFieldLazilyInitialized) {
+        if (instanceGetterMethod != null && !hasSynchronized(instanceGetterMethod, new HashSet<>()) && isInstanceFieldLazilyInitialized) {
```
Comment (iloveeclipse) [inline spotbugs/src/main/java/edu/umd/cs/findbugs/detect/MultipleInstantiationsOfSingletons.java:246]: Looking at this line, the call to the offending method would not be needed if `&& isInstanceFieldLazilyInitialized` condition would be evaluated first.

Comment (JuditKnoll) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/detect/MultipleInstantiationsOfSingletons.java:246]: I think the `hasSynchronized()` call is necessary here, as it checks whether the instance getter method is synchronized, and the `isInstanceFieldLazilyInitialized` doesn't contain this info. 
You are right about the order of different conditions. Thank you for highlighting this problem.

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+        assertBugInClass("SING_SINGLETON_GETTER_NOT_SYNCHRONIZED", "Issue3280");
```
Comment (JuditKnoll) [inline spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java:13]: The number of hits for the bugtype could be also checked: `assertBugTypeCount("SING_SINGLETON_GETTER_NOT_SYNCHRONIZED", 1);`

File: spotbugs/src/main/java/edu/umd/cs/findbugs/detect/MultipleInstantiationsOfSingletons.java (hunk 2 above)
Comment (gtoison) [reply spotbugs/src/main/java/edu/umd/cs/findbugs/detect/MultipleInstantiationsOfSingletons.java]: I have made the proposed reorderings with a small change on that one because the closing parenthesis after `isInstanceFieldLazilyInitialized` apparently got misplaced:
```
@@ -227,7 +228,5 @@
         if (!(hasSingletonPostFix
-                || (!javaClass.isAbstract() && !javaClass.isInterface() && !javaClass.isRecord()
-                        && isInstanceAssignOk
-                        && hasNoFactoryMethod
-                        && instanceGetterMethod != null
-                        && (isInstanceFieldEagerlyInitialized || isInstanceFieldLazilyInitialized)))) {
+                || (isInstanceAssignOk && hasNoFactoryMethod && instanceGetterMethod != null
+                        && (isInstanceFieldEagerlyInitialized || isInstanceFieldLazilyInitialized)))
+                        &&!javaClass.isAbstract() && !javaClass.isInterface() && !javaClass.isRecord()) {
```

File: spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java (hunk 3 above)
Comment (gtoison) [reply spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue3280Test.java]: You're right, I've made a change to assert the bug count and the type!

**Review by JuditKnoll — APPROVED** [review]

**Comment by iloveeclipse** [comment]
Thanks all.
