### PR TITLE
Fixed `DMI_INVOKING_TOSTRING_ON_ARRAY` on newer JDK

### LINKED ISSUE #1147: [false-negative]DMI_INVOKING_TOSTRING_ON_ARRAY can not detect String automatic conversion when string concatenation
**Affects SpotBugs Version:** 
spotbugs-4.0.0-RC2

**Rule:**
DMI_INVOKING_TOSTRING_ON_ARRAY

**Description:**
Unable to detect String automatic conversion when string concatenation, for example: <code>"foo" + barArray</code>,
This rule is implemented in SpotBugs.jar\main\java\edu\umd\cs\findbugs\detect\FindPuzzlers.java.
This rule uses the following code to detect explicit string conversion:
```
if (seen == Const.INVOKEVIRTUAL
                && stack.getStackDepth() > 0
                && ("toString".equals(getNameConstantOperand()) && "()Ljava/lang/String;".equals(getSigConstantOperand())
                        || "append".equals(getNameConstantOperand())
                                && "(Ljava/lang/Object;)Ljava/lang/StringBuilder;".equals(getSigConstantOperand())
                                && "java/lang/StringBuilder".equals(getClassConstantOperand())
                        || "append".equals(getNameConstantOperand())
                                && "(Ljava/lang/Object;)Ljava/lang/StringBuffer;".equals(getSigConstantOperand())
                                && "java/lang/StringBuffer".equals(getClassConstantOperand()) || ("print".equals(getNameConstantOperand())
                                        || "println".equals(getNameConstantOperand()))
                                        && "(Ljava/lang/Object;)V".equals(getSigConstantOperand())))
```
which includes the following 5 situations: 1.<code>toString</code>, 2.<code>StringBuilder.append(Object)</code>, 3.<code>StringBuffer.append(Object)</code>, 4.<code>print(Object)</code>, 5.<code>println(Object)</code>.
The string conversion performed during string concatenation is ignored.

**Code Sample demonstrating the issue:**
```
public void setRetrieveAttributes(String[] retrieveAttributes)
{
	LOGGER.debug("retrieveAttributes::" + retrieveAttributes);
}
```

**Expected outcome:**
false-negative

**Running SpotBugs through:**
command line

### PR DESCRIPTION
**Pull request by gtoison**
Detect the `String.valueOf(array)` call during string concatenation.

This should fix #1147

### CODE REVIEW

File: spotbugsTestCases/src/java/ghIssues/Issue1147.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package ghIssues;
+
+public class Issue1147 {
+
+	// Test for issues 1147 and 1874
```
Comment (JuditKnoll) [inline spotbugsTestCases/src/java/ghIssues/Issue1147.java:5]: #1874 isn't linked as fixed by this PR, but it seems to be a duplicate of #1147 to me. Was this intentionally left out?

**Review by JuditKnoll — APPROVED** [review]

File: spotbugsTestCases/src/java/ghIssues/Issue1147.java (hunk 1 above)
Comment (gtoison) [reply spotbugsTestCases/src/java/ghIssues/Issue1147.java:5]: This should fix #1874 too indeed!
