### PR TITLE
When AnalysisRunner has findbugs.xml in jar, don't create temp jar

### LINKED ISSUE #156: Enable tests disabled in #154
Tests FindNullDerefIntegrationTest and FindUnsatisfiedObligationTest were disabled in #154 (for #151) because they were failing due the issues with 
the new AnalysisRunner which seem to be confused by an unexpected findbugs.xml location:
`
java.lang.ExceptionInInitializerError
	at edu.umd.cs.findbugs.test.SpotBugsRule.before(SpotBugsRule.java:52)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at edu.umd.cs.findbugs.test.AnalysisRunner.createTempJar(AnalysisRunner.java:146)
	at edu.umd.cs.findbugs.test.AnalysisRunner.<clinit>(AnalysisRunner.java:61)
	... 36 more
`

### PR DESCRIPTION
**Pull request by kzaikin**
When AnalysisRunner is using spotbugs.jar, then there's no need to create temp jar for resources

fix #156

### CODE REVIEW

File: test-harness/src/main/java/edu/umd/cs/findbugs/test/AnalysisRunner.java [hunk 1]
```diff
@@ -133,17 +136,27 @@ public BugCollectionBugReporter run(Path... files) {
...
+     *
      * @return a {@link File} instance which represent generated jar file
      * @throws IOException
      * @throws URISyntaxException
      */
     private static File createTempJar() throws IOException, URISyntaxException {
         ClassLoader cl = AnalysisRunner.class.getClassLoader();
+
+        URL resource = cl.getResource("findbugs.xml");
+        URI uri = resource.toURI();
```
Comment (kzaikin) [inline test-harness/src/main/java/edu/umd/cs/findbugs/test/AnalysisRunner.java]: actually a resource might be null here, but I think it's ok to fall with NPE in tests when test configuration is unexpected

**Comment by kzaikin** [comment]
@KengoTODA I am not sure what should I do assign a reviewer. This PR fixes disabled tests
